export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const GET_ETH_BALANCE_SUCCESS = 'GET_ETH_BALANCE_SUCCESS';

export const STAKE_START = 'STAKE_START';

export const STAKE_SUCCESS = 'STAKE_SUCCESS';

export const UPDATE_USDT_BALANCE = 'UPDATE_USDT_BALANCE';

export const UPDATE_USDC_BALANCE = 'UPDATE_USDC_BALANCE';

export const UPDATE_DAI_BALANCE = 'UPDATE_DAI_BALANCE';

export const FETCH_LIQUIDITY_PROVIDER_SUCCESS =
  'FETCH_LIQUIDITY_PROVIDER_SUCCESS';

export const STAKE_APPROVE_START = 'STAKE_APPROVE_START';

export const STAKE_APPROVE_SUCCESS = 'STAKE_APPROVE_SUCCESS';

export const STAKE_APPROVE_FAILURE = 'STAKE_APPROVE_FAILURE';

export const STAKE_SEND_START = 'STAKE_SEND_START';

export const STAKE_SEND_SUCCESS = 'STAKE_SEND_SUCCESS';

export const STAKE_SEND_FAILURE = 'STAKE_SEND_FAILURE';

export const FETCH_RPT_BALANCE_SUCCESS = 'FETCH_RPT_BALANCE_SUCCESS';

export const CLAIM_MROYA_START = 'CLAIM_MROYA_START';

export const CLAIM_MROYA_SUCCESS = 'CLAIM_MROYA_SUCCESS';

export const CLAIM_MROYA_FAILURE = 'CLAIM_MROYA_FAILURE';

export const UNSTAKE_RTP_START = 'UNSTAKE_RTP_START';

export const UNSTAKE_RTP_SUCCESS = 'UNSTAKE_RTP_SUCCESS';

export const UNSTAKE_RTP_FAILURE = 'UNSTAKE_RTP_FAILURE';

export const STAKE_RTP_START = 'STAKE_RTP_START';

export const STAKE_RTP_SUCCESS = 'STAKE_RTP_SUCCESS';

export const SWITCH_RPT_STAKE_STEP = 'SWITCH_RPT_STAKE_STEP';

export const SWITCH_RPT_UNSTAKE_STEP = 'SWITCH_RPT_UNSTAKE_STEP';

export const STAKE_RTP_FAILURE = 'STAKE_RTP_FAILURE';

export const WITHDRAW_TOKEN_START = 'WITHDRAW_TOKEN_START';

export const WITHDRAW_TOKEN_SUCCESS = 'WITHDRAW_TOKEN_SUCCESS';

export const WITHDRAW_TOKEN_FAILURE = 'WITHDRAW_TOKEN_FAILURE';

export const SWITCH_WITHDRAW_STEP = 'SWITCH_WITHDRAW_STEP';

export const ROYA_RESERVE_STAKE_START = 'ROYA_RESERVE_STAKE_START';

export const ROYA_RESERVE_STAKE_SUCCESS = 'ROYA_RESERVE_STAKE_SUCCESS';

export const ROYA_RESERVE_STAKE_FAILURE = 'ROYA_RESERVE_STAKE_FAILURE';

export const GET_ROYA_STAKE_BALANCE_SUCCESS = 'GET_ROYA_STAKE_BALANCE_SUCCESS';

export const GET_ROYA_USER_BALANCE_SUCCESS = 'GET_ROYA_USER_BALANCE_SUCCESS';

export const GET_REWARD_BALANCE_SUCCESS = 'GET_REWARD_BALANCE_SUCCESS';

export const ACTIVATE_COOLDOWN_START = 'ACTIVATE_COOLDOWN_START';

export const ACTIVATE_COOLDOWN_SUCCESS = 'ACTIVATE_COOLDOWN_SUCCESS';

export const ACTIVATE_COOLDOWN_FAILURE = 'ACTIVATE_COOLDOWN_FAILURE';

export const CLAIM_ROYA_REWARD_START = 'CLAIM_ROYA_REWARD_START';

export const CLAIM_ROYA_REWARD_SUCCESS = 'CLAIM_ROYA_REWARD_SUCCESS';

export const CLAIM_ROYA_REWARD_FAILURE = 'CLAIM_ROYA_REWARD_FAILURE';

export const UNSTAKE_ROYA_RESERVE_START = 'UNSTAKE_ROYA_RESERVE_START';

export const UNSTAKE_ROYA_RESERVE_SUCCESS = 'UNSTAKE_ROYA_RESERVE_SUCCESS';

export const UNSTAKE_ROYA_RESERVE_FAILURE = 'UNSTAKE_ROYA_RESERVE_FAILURE';

export const SELL_KROYA_LOT_START = 'SELL_KROYA_LOT_START';

export const SELL_KROYA_LOT_SUCCESS = 'SELL_KROYA_LOT_SUCCESS';

export const SELL_KROYA_LOT_FAILURE = 'SELL_KROYA_LOT_FAILURE';

export const SELL_AROYA_LOT_START = 'SELL_AROYA_LOT_START';

export const SELL_AROYA_LOT_SUCCESS = 'SELL_AROYA_LOT_SUCCESS';

export const SELL_AROYA_LOT_FAILURE = 'SELL_AROYA_LOT_FAILURE';

export const SELL_MoROYA_LOT_START = 'SELL_MoROYA_LOT_START';

export const SELL_MoROYA_LOT_SUCCESS = 'SELL_MoROYA_LOT_SUCCESS';

export const SELL_MoROYA_LOT_FAILURE = 'SELL_MoROYA_LOT_FAILURE';

export const SELL_MROYA_LOT_START = 'SELL_MROYA_LOT_START';

export const SELL_MROYA_LOT_SUCCESS = 'SELL_MROYA_LOT_SUCCESS';

export const SELL_MROYA_LOT_FAILURE = 'SELL_MROYA_LOT_FAILURE';

export const SELL_SROYA_LOT_START = 'SELL_SROYA_LOT_START';

export const SELL_SROYA_LOT_SUCCESS = 'SELL_SROYA_LOT_SUCCESS';

export const SELL_SROYA_LOT_FAILURE = 'SELL_SROYA_LOT_FAILURE';

export const BUY_KROYA_LOT_START = 'BUY_KROYA_LOT_START';

export const BUY_DISCOUNTED_KROYA_LOT_START = 'BUY_DISCOUNTED_KROYA_LOT_START';

export const BUY_KROYA_LOT_SUCCESS = 'BUY_KROYA_LOT_SUCCESS';

export const BUY_KROYA_LOT_FAILURE = 'BUY_KROYA_LOT_FAILURE';

export const BUY_AROYA_LOT_START = 'BUY_AROYA_LOT_START';

export const BUY_AROYA_LOT_SUCCESS = 'BUY_AROYA_LOT_SUCCESS';

export const BUY_AROYA_LOT_FAILURE = 'BUY_AROYA_LOT_FAILURE';

export const BUY_MOROYA_LOT_START = 'BUY_MOROYA_LOT_START';

export const BUY_MOROYA_LOT_SUCCESS = 'BUY_MOROYA_LOT_SUCCESS';

export const BUY_MOROYA_LOT_FAILURE = 'BUY_MOROYA_LOT_FAILURE';

export const BUY_MROYA_LOT_START = 'BUY_MROYA_LOT_START';

export const BUY_MROYA_LOT_SUCCESS = 'BUY_MROYA_LOT_SUCCESS';

export const BUY_MROYA_LOT_FAILURE = 'BUY_MROYA_LOT_FAILURE';

export const BUY_SROYA_LOT_START = 'BUY_SROYA_LOT_START';

export const BUY_SROYA_LOT_SUCCESS = 'BUY_SROYA_LOT_SUCCESS';

export const BUY_SROYA_LOT_FAILURE = 'BUY_SROYA_LOT_FAILURE';

export const GET_USER_TOTAL_LOTS_SUCCESS = 'GET_USER_TOTAL_LOTS_SUCCESS';

export const GET_USER_LOT_REWARD = 'GET_USER_LOT_REWARD';

export const CLAIM_KLOT_REWARD_START = 'CLAIM_KLOT_REWARD_START';

export const CLAIM_KLOT_REWARD_SUCCESS = 'CLAIM_KLOT_REWARD_SUCCESS';

export const CLAIM_KLOT_REWARD_FAILURE = 'CLAIM_KLOT_REWARD_FAILURE';

export const CLAIM_ALOT_REWARD_START = 'CLAIM_ALOT_REWARD_START';

export const CLAIM_ALOT_REWARD_SUCCESS = 'CLAIM_ALOT_REWARD_SUCCESS';

export const CLAIM_ALOT_REWARD_FAILURE = 'CLAIM_ALOT_REWARD_FAILURE';

export const CLAIM_MoLOT_REWARD_START = 'CLAIM_MoLOT_REWARD_START';

export const CLAIM_MoLOT_REWARD_SUCCESS = 'CLAIM_MoLOT_REWARD_SUCCESS';

export const CLAIM_MoLOT_REWARD_FAILURE = 'CLAIM_MoLOT_REWARD_FAILURE';

export const CLAIM_MLOT_REWARD_START = 'CLAIM_MLOT_REWARD_START';

export const CLAIM_MLOT_REWARD_SUCCESS = 'CLAIM_MLOT_REWARD_SUCCESS';

export const CLAIM_MLOT_REWARD_FAILURE = 'CLAIM_MLOT_REWARD_FAILURE';

export const CLAIM_SLOT_REWARD_START = 'CLAIM_SLOT_REWARD_START';

export const CLAIM_SLOT_REWARD_SUCCESS = 'CLAIM_SLOT_REWARD_SUCCESS';

export const CLAIM_SLOT_REWARD_FAILURE = 'CLAIM_SLOT_REWARD_FAILURE';

export const FETCH_LIQUID_RPT_SUCCESS = 'FETCH_LIQUID_RPT_SUCCESS';

export const GET_USER_RPT = 'GET_USER_RPT';

export const GET_USER_STAKED_RPT = 'GET_USER_STAKED_RPT';

export const GET_USER_RPT_REWARD = 'GET_USER_RPT_REWARD';

export const CLOSE_SUCCESS_MSG = 'CLOSE_SUCCESS_MSG';

export const OPEN_ROYA_RESERVE_MODAL = 'OPEN_ROYA_RESERVE_MODAL';

export const CLOSED_ROYA_RESERVE_MODAL = 'CLOSED_ROYA_RESERVE_MODAL';

export const GET_COOLDOWN_STATUS_SUCCESS = 'GET_COOLDOWN_STATUS_SUCCESS';

export const GET_CONTRIBUTION_DYNAMICS_SUCCESS =
  'GET_CONTRIBUTION_DYNAMICS_SUCCESS';

export const GET_TOTAL_STAKED_ROYA_SUCCESS = 'GET_TOTAL_STAKED_ROYA_SUCCESS';

export const STAKERS_COOLDOWN_SUCCESS = 'STAKERS_COOLDOWN_SUCCESS';

export const GET_MROYA_BALANCE_SUCCESS = 'GET_MROYA_BALANCE_SUCCESS';

export const GET_TOTAL_RPT_SUPPLY_SUCCESS = 'GET_TOTAL_RPT_SUPPLY_SUCCESS';

export const GET_NFT_BALANCE_SUCCESS = 'GET_NFT_BALANCE_SUCCESS';

export const GET_NETWORK_LOT_SUCCESS = 'GET_NETWORK_LOT_SUCCESS';

export const GET_ROYA_STATS_SUCCESS = 'GET_ROYA_STATS_SUCCESS';

export const GET_TOTAL_STABLE_COIN_SUCCESS = 'GET_TOTAL_STABLE_COIN_SUCCESS';

export const GET_RPT_SUPPLY_SUCCESS = 'GET_RPT_SUPPLY_SUCCESS';

export const SET_NFT_ID = 'SET_NFT_ID';

export const GET_LOCKED_NFT_SUCCESS = 'GET_LOCKED_NFT_SUCCESS';

export const SELL_LOCKED_KNIGHT_NFT_START = 'SELL_LOCKED_KNIGHT_NFT_START';

export const GET_DISCOUNTED_KNIGHT_LOT_SUCCESS =
  'GET_DISCOUNTED_KNIGHT_LOT_SUCCESS';

export const CLAIM_TOKENS_START = 'CLAIM_TOKENS_START';

export const CLAIM_TOKENS_SUCCESS = 'CLAIM_TOKENS_SUCCESS';

export const CLAIM_TOKENS_FAILURE = 'CLAIM_TOKENS_FAILURE';

export const GET_ISCLAIMABLE_SUCCESS = 'GET_ISCLAIMABLE_SUCCESS';

export const GET_TOTAL_ROYA_HOLDERS_SUCCESS = 'GET_TOTAL_ROYA_HOLDERS_SUCCESS';

export const GET_CLAIMABLE_BALANCE_SUCCESS = 'GET_CLAIMABLE_BALANCE_SUCCESS';

export const GET_ROYALE_LIQUID_SUCCESS = 'GET_ROYALE_LIQUID_SUCCESS';

export const GET_TOTAL_MROYA_SUCCESS = 'GET_TOTAL_MROYA_SUCCESS';

export const GET_RPT_DYNAMICS_SUCCESS = 'GET_RPT_DYNAMICS_SUCCESS';

export const GET_ROYA_DYNAMICS_SUCCESS = 'GET_ROYA_DYNAMICS_SUCCESS';

export const GET_RPT_TO_USD_SUCCESS = 'GET_RPT_TO_USD_SUCCESS';

export const UPDATE_BUSD_BALANCE = 'UPDATE_BUSD_BALANCE';

export const GET_OPTIMISER_LIQUIDITY_SUCCESS =
  'GET_OPTIMISER_LIQUIDITY_SUCCESS';

export const GET_GAMING_LIQUIDITY_SUCCESS = 'GET_GAMING_LIQUIDITY_SUCCESS';

export const GET_GLOBAL_ROYA_PROTOCOL_SUCCESS =
  'GET_GLOBAL_ROYA_PROTOCOL_SUCCESS';

export const SWAP_MROYA_TOKEN_START = 'SWAP_MROYA_TOKEN_START';

export const SWAP_MROYA_TOKEN_SUCCESS = 'SWAP_MROYA_TOKEN_SUCCESS';

export const SWAP_MROYA_TOKEN_FAILURE = 'SWAP_MROYA_TOKEN_FAILURE';

export const GET_RPT_REWARDS_SUCCESS = 'GET_RPT_REWARDS_SUCCESS';

export const GET_REWARDS_DAYS_LEFT_SUCCESS = 'GET_REWARDS_DAYS_LEFT_SUCCESS';

export const GET_STAKED_RPT_USDC = 'GET_STAKED_RPT_USDC';

export const GET_REWARD_RATE_SUCCESS = 'GET_REWARD_RATE_SUCCESS';

export const MENTIONLYTICS_API_START = `MENTIONLYTICS_API_START`;

export const MENTIONLYTICS_API_SUCCESS = `MENTIONLYTICS_API_SUCCESS`;

export const MENTIONLYTICS_API_FAILURE = `MENTIONLYTICS_API_FAILURE`;

export const GET_MENTIONLYTICS_API = 'GET_MENTIONLYTICS_API';

export const USER_REGISTER_START = `USER_REGISTER_START`;

export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';

export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE';

export const GET_POOL_CONTRACT_START = `GET_POOL_CONTRACT_START`;

export const GET_POOL_CONTRACT_SUCCESS = 'GET_POOL_CONTRACT_SUCCESS';

export const GET_POOL_CONTRACT_FAILURE = 'GET_POOL_CONTRACT_FAILURE';

export const GET_SWAP_DATA_START = `GET_SWAP_DATA_START`;

export const GET_SWAP_DATA_SUCCESS = 'GET_SWAP_DATA_SUCCESS';

export const GET_SWAP_DATA_FAILURE = 'GET_SWAP_DATA_FAILURE';
